name = "BigWig"
uuid = "9d649c22-cb6b-11e8-1fa9-f3896fced444"
authors = ["Kenta Sato <bicycle1885@gmail.com>", "Ben J. Ward <benjward@protonmail.com>", "Ciar√°n O'Mara <Ciaran.OMara@utas.edu.au>"]
version = "0.1.0"
